/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zhengzhiren_android_hardware_Framebuffer */

#ifndef _Included_zhengzhiren_android_hardware_Framebuffer
#define _Included_zhengzhiren_android_hardware_Framebuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     zhengzhiren_android_hardware_Framebuffer
 * Method:    getFramebuffer
 * Signature: (Ljava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_zhengzhiren_android_hardware_Framebuffer_getFramebuffer
  (JNIEnv *, jclass, jobject);

/*
 * Class:     zhengzhiren_android_hardware_Framebuffer
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zhengzhiren_android_hardware_Framebuffer_getWidth
  (JNIEnv *, jclass);

/*
 * Class:     zhengzhiren_android_hardware_Framebuffer
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zhengzhiren_android_hardware_Framebuffer_getHeight
  (JNIEnv *, jclass);

/*
 * Class:     zhengzhiren_android_hardware_Framebuffer
 * Method:    getBytesPerPixel
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_zhengzhiren_android_hardware_Framebuffer_getBytesPerPixel
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
